name: login_registar_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0  
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  svg_flutter: ^0.0.1
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  url_launcher: ^6.2.4
  syncfusion_flutter_pdfviewer: ^24.1.41
  file_picker: ^6.1.1
  image_picker: ^0.8.5+3
  http_parser: ^4.0.2
  android_intent_plus: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/icons/
